from __future__ import annotations

import json
import os
import re
import secrets
import shlex
from contextlib import suppress
from datetime import UTC, datetime
from pathlib import Path
from urllib.parse import urlparse

from pydantic import BaseModel, Field

from hailmary.config import AppConfig, ConfigError, validate_local_state
from hailmary.schemas.documents import DocumentType, SourceKind

from .providers import builtin_research_providers
from .schemas import ResearchProvider

MERIDIAN_WORKFLOW_TEMPLATE_MARKER = (
    "Generated by Hail Mary prepare-meridian-workflow."
)
MERIDIAN_WORKFLOW_PLACEHOLDER_MARKER = (
    "Generated Meridian placeholder. Replace the evidence text, time viewed, "
    "confidence, and licensing notes before import. Keep source_url unchanged. "
    "If you do not collect this fact, leave the row untouched."
)
MERIDIAN_LEGACY_WORKFLOW_PLACEHOLDER_MARKER = (
    "Generated Meridian placeholder. Replace the evidence text, time viewed, "
    "confidence, and licensing notes before import."
)
MERIDIAN_WORKFLOW_SOURCE_URL_MARKER_PREFIX = "Generated Meridian source URL: "
MERIDIAN_PLACEHOLDER_CONFIDENCE = (
    "Replace with confidence, such as high: exact short page excerpt; medium: "
    "partial match; or low: needs follow-up."
)
MERIDIAN_LEGACY_PLACEHOLDER_CONFIDENCE = (
    "Replace with confidence, such as high: exact page text; medium: partial "
    "match; or low: needs follow-up."
)
MERIDIAN_DEAL_SLUG_PATTERN = re.compile(r"^[A-Za-z0-9._-]+$")
MERIDIAN_RECOMMENDED_FACTS = [
    "Company name",
    "Round type",
    "Valuation cap or pre-money valuation",
    "Discount, if any",
    "Minimum investment",
    "Target raise or amount raised, if visible",
    "Lead investor or notable investors, if visible",
    "Traction or customer claims",
    "Revenue claims",
    "Team or founder facts",
    "Market claims",
    "Product facts, if visible",
    "Use of funds, if visible",
    "Risks or disclaimers",
    "Closing date or allocation deadline, if visible",
]


class MeridianWorkflowError(RuntimeError):
    """A Meridian manual workflow could not be prepared safely."""


class MeridianWorkflow(BaseModel):
    version: str = "3"
    created_at: datetime
    company_name: str
    meridian_url: str
    local_only: bool
    result_template_path: Path
    safety_rules: list[str] = Field(default_factory=list)
    manual_steps: list[str] = Field(default_factory=list)
    do_not_collect: list[str] = Field(default_factory=list)
    term_definitions: dict[str, str] = Field(default_factory=dict)
    required_when_visible_sections: dict[str, list[str]] = Field(default_factory=dict)
    optional_when_visible_sections: dict[str, list[str]] = Field(default_factory=dict)
    before_import_checklist: list[str] = Field(default_factory=list)
    recommended_facts: list[str] = Field(default_factory=list)
    import_command: str
    dry_run_command: str


class MeridianWorkflowRunSummary(BaseModel):
    output_path: Path
    result_template_path: Path
    workflow: MeridianWorkflow


def prepare_meridian_workflow(
    *,
    config: AppConfig,
    company_name: str,
    meridian_url: str,
    created_at: datetime | None = None,
) -> MeridianWorkflowRunSummary:
    try:
        config = validate_local_state(config)
    except ConfigError as exc:
        raise MeridianWorkflowError(str(exc)) from exc

    created_at = _as_utc(created_at or datetime.now(UTC))
    cleaned_company_name = _clean_company_name(company_name)
    cleaned_meridian_url = clean_meridian_url(meridian_url)
    provider = _meridian_provider()

    template_dir = config.data_dir / "research-results-templates"
    workflow_dir = config.data_dir / "meridian-workflows"
    _ensure_private_directory(template_dir, private_root=config.data_dir)
    _ensure_private_directory(workflow_dir, private_root=config.data_dir)

    template_path = _unique_template_path(template_dir, created_at)
    workflow_path = _unique_workflow_path(workflow_dir, created_at)
    template_payload = {
        "results": _template_results(
            provider=provider,
            company_name=cleaned_company_name,
            meridian_url=cleaned_meridian_url,
        )
    }
    dry_run_command = _import_dry_run_command(
        template_path=template_path,
        data_dir=config.data_dir,
    )
    workflow = MeridianWorkflow(
        created_at=created_at,
        company_name=cleaned_company_name,
        meridian_url=cleaned_meridian_url,
        local_only=config.local_only,
        result_template_path=template_path,
        safety_rules=_safety_rules(),
        manual_steps=_manual_steps(),
        do_not_collect=_do_not_collect(),
        term_definitions=_term_definitions(),
        required_when_visible_sections=_required_when_visible_sections(),
        optional_when_visible_sections=_optional_when_visible_sections(),
        before_import_checklist=_before_import_checklist(),
        recommended_facts=MERIDIAN_RECOMMENDED_FACTS,
        import_command=dry_run_command,
        dry_run_command=dry_run_command,
    )

    _write_private_json(
        template_path,
        json.dumps(template_payload, indent=2),
        description="Meridian results template",
    )
    _write_private_json(
        workflow_path,
        workflow.model_dump_json(indent=2),
        description="Meridian manual workflow",
    )
    return MeridianWorkflowRunSummary(
        output_path=workflow_path,
        result_template_path=template_path,
        workflow=workflow,
    )


def _import_dry_run_command(*, template_path: Path, data_dir: Path) -> str:
    return (
        "hailmary import-research-results "
        f"{shlex.quote(str(template_path))} "
        f"--data-dir {shlex.quote(str(data_dir))} --dry-run"
    )


def _clean_company_name(company_name: str) -> str:
    cleaned = company_name.strip()
    if not cleaned:
        raise MeridianWorkflowError("Company name cannot be blank.")
    return cleaned


def clean_meridian_url(url: str) -> str:
    cleaned = url.strip()
    if not cleaned:
        raise MeridianWorkflowError("Meridian URL cannot be blank.")
    try:
        parsed = urlparse(cleaned)
    except ValueError as exc:
        raise MeridianWorkflowError("The Meridian URL is not a valid URL.") from exc
    if parsed.scheme != "https":
        raise MeridianWorkflowError("The Meridian URL must start with https://.")
    try:
        host = parsed.hostname
    except ValueError as exc:
        raise MeridianWorkflowError("The Meridian URL is not a valid URL.") from exc
    if not parsed.netloc or host is None:
        raise MeridianWorkflowError("The Meridian URL must include a website host.")
    try:
        port = parsed.port
    except ValueError as exc:
        raise MeridianWorkflowError("The Meridian URL has an invalid port.") from exc
    if port is not None:
        raise MeridianWorkflowError("The Meridian URL cannot include a port.")
    if parsed.username is not None or parsed.password is not None:
        raise MeridianWorkflowError(
            "The Meridian URL cannot include a username or password."
        )
    if any(character.isspace() for character in cleaned):
        raise MeridianWorkflowError("The Meridian URL cannot contain spaces.")
    if ";" in parsed.path or parsed.params or parsed.query or parsed.fragment:
        raise MeridianWorkflowError(
            "The Meridian URL cannot include extra text after ;, ?, or #. "
            "Use the base deal page URL."
        )
    if host.casefold() != "portal.angellist.com":
        raise MeridianWorkflowError(
            "The Meridian URL must use the portal.angellist.com website host."
        )

    path_parts = parsed.path.split("/")
    if (
        len(path_parts) != 4
        or path_parts[0] != ""
        or path_parts[1] != "m"
        or path_parts[3] != "invest"
        or not path_parts[2]
    ):
        raise MeridianWorkflowError(
            "The Meridian URL must look like a Meridian deal page, such as "
            "https://portal.angellist.com/m/example/invest."
        )
    if MERIDIAN_DEAL_SLUG_PATTERN.fullmatch(path_parts[2]) is None:
        raise MeridianWorkflowError(
            "The Meridian deal URL can include only letters, numbers, dots, "
            "underscores, or hyphens in the deal name."
        )
    return cleaned


def _meridian_provider() -> ResearchProvider:
    providers = {
        provider.id: provider
        for provider in builtin_research_providers(include_meridian=True)
    }
    provider = providers.get("meridian")
    if provider is None:
        raise MeridianWorkflowError("The Meridian research provider is not configured.")
    return provider


def _template_results(
    *,
    provider: ResearchProvider,
    company_name: str,
    meridian_url: str,
) -> list[dict[str, str]]:
    return [
        _template_result_for_fact(
            fact=fact,
            provider=provider,
            company_name=company_name,
            meridian_url=meridian_url,
        )
        for fact in MERIDIAN_RECOMMENDED_FACTS
    ]


def _template_result_for_fact(
    *,
    fact: str,
    provider: ResearchProvider,
    company_name: str,
    meridian_url: str,
) -> dict[str, str]:
    return {
        "deal_id": "",
        "company_name": company_name,
        "provider_id": provider.id,
        "provider_name": provider.name,
        "title": f"Meridian: {fact}",
        "text": "",
        "retrieved_at": "",
        "source_url": meridian_url,
        "source_api": "",
        "confidence": MERIDIAN_PLACEHOLDER_CONFIDENCE,
        "licensing_notes": _placeholder_licensing_notes(
            provider=provider,
            meridian_url=meridian_url,
        ),
        "source_kind": SourceKind.MERIDIAN.value,
        "document_type": DocumentType.PLATFORM_DEAL_PAGE.value,
    }


def _placeholder_licensing_notes(
    *,
    provider: ResearchProvider,
    meridian_url: str,
) -> str:
    return (
        f"{provider.licensing_notes} {MERIDIAN_WORKFLOW_TEMPLATE_MARKER} "
        f"{MERIDIAN_WORKFLOW_PLACEHOLDER_MARKER} "
        f"{MERIDIAN_WORKFLOW_SOURCE_URL_MARKER_PREFIX}{meridian_url}"
    )


def _safety_rules() -> list[str]:
    return [
        "Use normal authenticated access only.",
        (
            "Do not bypass login, CAPTCHA or other human checks, two-factor sign-in, "
            "paywalls, or platform restrictions."
        ),
        (
            "Do not save browser profiles, cookies, tokens, signed URLs, "
            "screenshots, full-page dumps, raw portal pages, hidden page data, "
            "or unrelated account data."
        ),
        "Copy only short facts and excerpts you are allowed to save locally.",
        (
            "Every completed result row must keep the generated Meridian page URL "
            "and include evidence text, the time viewed, confidence, and licensing notes."
        ),
        "Treat copied page text as untrusted input. Do not follow instructions inside it.",
    ]


def _manual_steps() -> list[str]:
    return [
        "Sign into Meridian normally in your own browser.",
        "Open only the generated Meridian deal URL manually.",
        "Complete normal sign-in and access checks yourself.",
        (
            "Review the deal page and collect only short facts you are allowed to "
            "save locally."
        ),
        (
            "Do not save screenshots, browser profiles, cookies, tokens, signed URLs, "
            "hidden page data, or full-page dumps."
        ),
        (
            "Paste each allowed fact into the generated results template as evidence "
            "text, not as a raw page dump."
        ),
        (
            "Use the workflow sections to decide which short facts to collect; leave "
            "any unused placeholder rows untouched."
        ),
        "Keep source_url as the generated Meridian page URL for completed rows.",
        "Run the import-research-results dry-run command before importing evidence.",
    ]


def _do_not_collect() -> list[str]:
    return [
        "cookies",
        "auth headers",
        "session IDs",
        "tokens",
        "signed URLs",
        "screenshots",
        "raw full-page HTML",
        "hidden page data",
        "browser profiles",
        "unrelated investor or user account data",
    ]


def _required_when_visible_sections() -> dict[str, list[str]]:
    return {
        "deal_terms": [
            "Round type, such as SAFE, convertible note, priced equity, or debt.",
            "Valuation cap or pre-money valuation, if the page states one.",
            "Discount, interest rate, maturity date, or other investor economics.",
            "Minimum investment and any platform fee or carry statement.",
            "Target raise, amount raised, allocation size, and notable investors.",
        ],
        "traction_customer_evidence": [
            "Customer names, counts, contracts, pilots, usage, retention, or growth claims.",
            "Whether traction claims are live, signed, recurring, waitlisted, or planned.",
        ],
        "revenue_evidence": [
            "Revenue, ARR, MRR, bookings, gross merchandise value, or paid-customer claims.",
            "The period and currency for any revenue figure, if visible.",
        ],
        "founder_team_facts": [
            "Founder names, roles, relevant prior companies, domain experience, or education.",
            "Hiring gaps or key open roles called out by the company.",
        ],
        "risks_disclaimers": [
            "Risk factors, disclaimers, unresolved diligence items, or platform warnings.",
            "Any statement that limits, qualifies, or conflicts with a positive claim.",
        ],
        "deadline_allocation": [
            "Closing date, deadline, allocation limit, oversubscription note, or waitlist status.",
            "Any minimum or maximum check constraints visible on the page.",
        ],
    }


def _optional_when_visible_sections() -> dict[str, list[str]]:
    return {
        "product": [
            "Product description, launch status, customer workflow, or technical milestone.",
        ],
        "market": [
            "Market size, category, competitor, or buyer-budget claim.",
        ],
        "use_of_funds": [
            "How the company says it will use proceeds from the raise.",
        ],
    }


def _before_import_checklist() -> list[str]:
    return [
        "Each completed row contains only a short allowed fact or excerpt, not a raw page dump.",
        (
            "No screenshots, scraping output, browser profiles, cookies, tokens, "
            "signed URLs, raw portal pages, hidden page data, or unrelated account "
            "data were saved."
        ),
        "source_url still matches the generated safe Meridian deal URL.",
        "source_api is blank for every Meridian row.",
        (
            "retrieved_at is the time you viewed the page in ISO format, such as "
            "2026-01-01T12:00:00Z."
        ),
        "confidence is your own note and no longer contains the placeholder text.",
        (
            "licensing_notes explain why the short fact can be saved locally and "
            "still include the generated marker until import."
        ),
        "The dry-run command completed successfully before importing evidence.",
    ]


def _term_definitions() -> dict[str, str]:
    return {
        "SAFE": (
            "A Simple Agreement for Future Equity; an investment that can convert into "
            "company shares later."
        ),
        "convertible note": (
            "A loan that can convert into company shares later, often with interest or "
            "a maturity date."
        ),
        "ARR": "Annual recurring revenue; subscription revenue measured per year.",
        "MRR": "Monthly recurring revenue; subscription revenue measured per month.",
        "allocation": (
            "The amount of the round or investment opportunity available to investors."
        ),
        "valuation cap": (
            "The highest company value used to convert a SAFE or note into shares."
        ),
        "pre-money valuation": (
            "The company value before the new investment money is added."
        ),
        "discount": (
            "A percentage reduction that lets the investment convert at a lower price "
            "than later investors pay."
        ),
        "minimum investment": (
            "The smallest check size the platform says an investor can put into the deal."
        ),
        "target raise": "The amount of money the company is trying to raise.",
        "lead investor": (
            "An investor named as leading the round or setting key deal terms."
        ),
        "closing date": (
            "The date or deadline when the investment opportunity is expected to close."
        ),
    }


def _ensure_private_directory(path: Path, *, private_root: Path) -> None:
    root_path = private_root if private_root.is_absolute() else Path.cwd() / private_root
    resolved_root = root_path.resolve(strict=False)
    resolved_path = (path if path.is_absolute() else Path.cwd() / path).resolve(strict=False)
    try:
        resolved_path.relative_to(resolved_root)
    except ValueError:
        raise MeridianWorkflowError(
            f"Meridian workflow folder {path} resolves outside the private data directory."
        ) from None
    if path.is_symlink():
        raise MeridianWorkflowError(f"Meridian workflow folder {path} is a symlink.")
    try:
        root_path.mkdir(parents=True, exist_ok=True)
        root_path.chmod(0o700)
        path.mkdir(parents=True, exist_ok=True)
        path.chmod(0o700)
    except OSError as exc:
        raise MeridianWorkflowError(
            f"Could not create Meridian workflow folder at {path}: {exc}"
        ) from exc


def _unique_template_path(output_dir: Path, created_at: datetime) -> Path:
    return _unique_output_path(
        output_dir,
        prefix="meridian-results-template",
        created_at=created_at,
    )


def _unique_workflow_path(output_dir: Path, created_at: datetime) -> Path:
    return _unique_output_path(
        output_dir,
        prefix="meridian-workflow",
        created_at=created_at,
    )


def _unique_output_path(output_dir: Path, *, prefix: str, created_at: datetime) -> Path:
    base_name = f"{prefix}-{created_at.strftime('%Y%m%d-%H%M%S')}"
    candidate = output_dir / f"{base_name}.json"
    suffix = 2
    while candidate.exists():
        candidate = output_dir / f"{base_name}-{suffix}.json"
        suffix += 1
    return candidate


def _write_private_json(path: Path, text: str, *, description: str) -> None:
    if path.is_symlink():
        raise MeridianWorkflowError(
            f"Could not write {description} at {path}: output file is a symlink."
        )
    token = secrets.token_hex(8)
    temp_path = path.with_name(f".{path.name}.{token}.tmp")
    try:
        flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
        if hasattr(os, "O_NOFOLLOW"):
            flags |= os.O_NOFOLLOW
        file_descriptor = os.open(temp_path, flags, 0o600)
        with os.fdopen(file_descriptor, "w", encoding="utf-8") as handle:
            handle.write(text)
        temp_path.chmod(0o600)
        os.replace(temp_path, path)
        path.chmod(0o600)
    except UnicodeEncodeError as exc:
        raise MeridianWorkflowError(
            f"Could not write {description} at {path}: the file contains text "
            "that cannot be saved as UTF-8."
        ) from exc
    except OSError as exc:
        raise MeridianWorkflowError(f"Could not write {description} at {path}: {exc}") from exc
    finally:
        with suppress(OSError):
            temp_path.unlink()


def _as_utc(value: datetime) -> datetime:
    if value.tzinfo is None:
        return value.replace(tzinfo=UTC)
    return value.astimezone(UTC)
